_task:
  # _task
  # DEFAULT_ZWA: 被动 早晚安 进群默认开关状态
  # DEFAULT_BROADCAST: 被动 广播 进群默认开关状态
  # DEFAULT_GROUP_WELCOME: 被动 进群欢迎 进群默认开关状态
  # DEFAULT_REFUND_GROUP_REMIND: 被动 退群提醒 进群默认开关状态
  # DEFAULT_FUDU: 被动 复读 进群默认开关状态
  DEFAULT_ZWA: true
  DEFAULT_BROADCAST: true
  DEFAULT_GROUP_WELCOME: true
  DEFAULT_REFUND_GROUP_REMIND: true
  DEFAULT_FUDU: true
_backup:
  # 文件备份
  # BACKUP_FLAG: 是否开启文件备份
  # BACKUP_DIR_OR_FILE: 备份的文件夹或文件
  BACKUP_FLAG: true
  BACKUP_DIR_OR_FILE:
  - data/black_word
  - data/configs
  - data/statistics
  - data/word_bank
  - data/manager
  - configs
chat_history:
  # 消息存储
  # FLAG: 是否开启消息自从存储
  FLAG: true
group_manager:
  # group_manager
  # DEFAULT_GROUP_LEVEL: 默认群权限
  # DEFAULT_GROUP_BOT_STATUS: 默认进群总开关状态
  DEFAULT_GROUP_LEVEL: 5
  DEFAULT_GROUP_BOT_STATUS: true
shop:
  # shop
  # IMPORT_DEFAULT_SHOP_GOODS: 导入商店自带的三个商品
  IMPORT_DEFAULT_SHOP_GOODS: true
hook:
  # 基础hook配置
  # CHECK_NOTICE_INFO_CD: 群检测，个人权限检测等各种检测提示信息cd
  # MALICIOUS_BAN_TIME: 恶意命令触发检测触发后ban的时长（分钟）
  # MALICIOUS_CHECK_TIME: 恶意命令触发检测规定时间内（秒）
  # MALICIOUS_BAN_COUNT: 恶意命令触发检测最大触发次数
  # BAN_RESULT: 对被ban用户发送的消息
  CHECK_NOTICE_INFO_CD: 300
  MALICIOUS_BAN_TIME: 30
  MALICIOUS_CHECK_TIME: 5
  MALICIOUS_BAN_COUNT: 6
  BAN_RESULT: 才不会给你发消息.
admin_bot_manage:
  # 群管理员操作
  # SET_GROUP_WELCOME_MESSAGE_LEVEL: 设置群欢迎消息权限
  # CHANGE_GROUP_SWITCH_LEVEL: 开关群功能权限
  # ADMIN_DEFAULT_AUTH: 默认群管理员权限
  SET_GROUP_WELCOME_MESSAGE_LEVEL: 2
  CHANGE_GROUP_SWITCH_LEVEL: 2
  ADMIN_DEFAULT_AUTH: 5
invite_manager:
  # 好友群聊处理请求
  # MESSAGE: 强制拉群后进群回复的内容..
  # FLAG: 被强制拉群后是否直接退出
  # WELCOME_MSG_CD: 群欢迎消息cd
  # AUTO_ADD_FRIEND: 是否自动同意好友添加
  MESSAGE: 请不要未经同意就拉小真寻入群！告辞！
  FLAG: true
  WELCOME_MSG_CD: 5
  AUTO_ADD_FRIEND: false
black_word:
  # 敏感词检测与惩罚
  # CYCLE_DAYS: 黑名单词汇记录周期
  # TOLERATE_COUNT: 各个级别惩罚的容忍次数，依次为：1, 2, 3, 4, 5
  # AUTO_PUNISH: 是否启动自动惩罚机制
  # BAN_4_DURATION: Union[int, List[int, int]]Ban时长（分钟），四级惩罚，可以为指定数字或指定列表区间(随机)，例如 [30, 360]
  # BAN_3_DURATION: Union[int, List[int, int]]Ban时长（天），三级惩罚，可以为指定数字或指定列表区间(随机)，例如 [7, 30]
  # WARNING_RESULT: 口头警告内容
  # AUTO_ADD_PUNISH_LEVEL: 自动提级机制，当周期内处罚次数大于某一特定值就提升惩罚等级
  # ADD_PUNISH_LEVEL_TO_COUNT: 在CYCLE_DAYS周期内触发指定惩罚次数后提升惩罚等级
  # ALAPI_CHECK_FLAG: 当未检测到已收录的敏感词时，开启ALAPI文本检测并将疑似文本发送给超级用户
  # CONTAIN_BLACK_STOP_PROPAGATION: 当文本包含任意敏感词时，停止向下级插件传递，即不触发ai
  CYCLE_DAYS: 30
  TOLERATE_COUNT:
  - 5
  - 1
  - 1
  - 1
  - 1
  AUTO_PUNISH: true
  BAN_4_DURATION: 360
  BAN_3_DURATION: 7
  WARNING_RESULT: 请注意对小真寻的发言内容
  AUTO_ADD_PUNISH_LEVEL: true
  ADD_PUNISH_LEVEL_TO_COUNT: 3
  ALAPI_CHECK_FLAG: false
  CONTAIN_BLACK_STOP_PROPAGATION: true
word_clouds:
  # 词云
  # WORD_CLOUDS_TEMPLATE: 词云模板 参1：图片生成，默认使用真寻图片，可在项目路径resources/image/wordcloud下配置图片，多张则随机 | 参2/其他：黑底图片
  WORD_CLOUDS_TEMPLATE: 1
ban:
  # 封禁Ban用户
  # BAN_LEVEL [LEVEL]: ban/unban所需要的管理员权限等级
  BAN_LEVEL [LEVEL]: 5
nickname:
  # 昵称系统
  # BLACK_WORD: 昵称所屏蔽的关键词，会被替换为 *
  BLACK_WORD:
  - 爸
  - 爹
  - 爷
  - 父亲
sign_in:
  # 签到
  # MAX_SIGN_GOLD: 签到好感度加成额外获得的最大金币数
  # SIGN_CARD1_PROB: 签到好感度双倍加持卡Ⅰ掉落概率
  # SIGN_CARD2_PROB: 签到好感度双倍加持卡Ⅱ掉落概率
  # SIGN_CARD3_PROB: 签到好感度双倍加持卡Ⅲ掉落概率
  MAX_SIGN_GOLD: 200
  SIGN_CARD1_PROB: 0.2
  SIGN_CARD2_PROB: 0.09
  SIGN_CARD3_PROB: 0.05
reload_setting:
  # 重载插件配置
  # AUTO_RELOAD: 自动重载配置文件
  # AUTO_RELOAD_TIME: 控制自动重载配置文件时长
  AUTO_RELOAD: false
  AUTO_RELOAD_TIME: 180
fudu:
  # 复读
  # FUDU_PROBABILITY: 复读概率
  FUDU_PROBABILITY: 0.7
